# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20190424_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='originalimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='originalimages'),
            preserve_default=False,
        ),
    ]
