# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-08 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_originalimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-upvotes', 'name']},
        ),
        migrations.AddField(
            model_name='product',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
